version: '3.8'

services:
  app:
    build: .
    container_name: beelife-app
    ports:
      - "8080:8080"  # Map port 8080 của container ra port 8080 của host
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://14.225.220.60:3306/beelifeventures?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=beelife_user
      - SPRING_DATASOURCE_PASSWORD=dfjsdbA3f@a!@#sdb
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - beelife-network

networks:
  beelife-network:
    driver: bridge
